export const SCAN_SURFACE_SCRIPT = [
  "(function(){",
  "function clean(text){if(!text)return '';return text.trim().replace(/\\s+/g,' ');}",
  "function isValid(text){var value=clean(text);if(!value)return false;if(/^\\d+$/.test(value))return false;if(value.length<=2)return false;var noise=new Set(['...','|','-','--','>>','<<','>','<']);return !noise.has(value);}",
  "function collectUnique(selector,getText){var out=[];document.querySelectorAll(selector).forEach(function(el){var text=clean(getText(el));if(isValid(text)&&out.indexOf(text)===-1)out.push(text);});return out.sort(function(a,b){return a.localeCompare(b);});}",
  "var h1=document.querySelector('h1');var title=clean(h1&&h1.textContent||'')||clean(document.title);",
  "var headings=collectUnique('h1,h2,h3',function(el){return el.textContent||'';});",
  "var ignoredButtons=new Set(['Dashboard','Home','Logout','Profile']);",
  "var buttons=collectUnique('button, input[type=\"button\"], input[type=\"submit\"], [role=\"button\"]',function(el){return el.textContent||el.getAttribute('value')||el.getAttribute('aria-label')||'';}).filter(function(text){return !ignoredButtons.has(text);});",
  "var searchBoxes=[];document.querySelectorAll('input').forEach(function(el){var placeholder=clean(el.getAttribute('placeholder')||'');if(placeholder&&searchBoxes.indexOf(placeholder)===-1)searchBoxes.push(placeholder);});",
  "var tableHeaders=collectUnique('th, [role=\"columnheader\"], caption',function(el){return el.textContent||el.getAttribute('aria-label')||'';});",
  "var formFields=collectUnique('input, textarea, select, label',function(el){return el.textContent||el.getAttribute('placeholder')||el.getAttribute('aria-label')||el.getAttribute('name')||el.getAttribute('id')||'';});",
  "var tableCount=document.querySelectorAll('table').length;",
  "var cardSelector=['.card','.dashboard-card','.MuiCard-root','.ant-card','.panel','article','[class*=\"card\"]'].join(',');",
  "var cards=[];document.querySelectorAll(cardSelector).forEach(function(el){var raw=clean(el.textContent||'').split('\\n')[0];if(isValid(raw)&&cards.indexOf(raw)===-1)cards.push(raw);});cards.sort(function(a,b){return a.localeCompare(b);});",
  "var badges=collectUnique('.badge, .chip, .status, .tag',function(el){return el.textContent||'';});",
  "var tabs=collectUnique('[role=\"tab\"], .tab',function(el){return el.textContent||'';});",
  "var chartSelector=['.recharts-wrapper','.apexcharts-canvas','.highcharts-container','.echarts-for-react','.chart-container','canvas.chartjs-render-monitor','[data-testid*=\"chart\"]'].join(',');",
  "var chartCount=0;document.querySelectorAll(chartSelector).forEach(function(el){var rect=el.getBoundingClientRect();if(rect.width>0&&rect.height>0)chartCount+=1;});",
  "return {url:window.location.href,title:title,headings:headings,buttons:buttons,searchBoxes:searchBoxes,tableHeaders:tableHeaders,formFields:formFields,tableCount:tableCount,cards:cards,badges:badges,tabs:tabs,chartCount:chartCount};",
  "})()",
].join("");
